### ISSUE TITLE
Can you add a world game mode?  gamemode: adventure

### ISSUE THREAD

**Issue by Cqmmls** [lokka30/PhantomWorlds#42]
```yaml
advanced:
  file-version: 2
  generated-with: 2.0.4
worlds-to-load:
  world_game:
    environment: NORMAL
    generateStructures: true
    hardcore: false
    worldType: NORMAL
    spawnMobs: true
    spawnAnimals: true
    keepSpawnInMemory: falsea
    allowPvP: true
    difficulty: NORMAL
    gamemode: adventure  # <----------
```
